server:
  port: 8000

#nacos地址,单机模式
nacos:
  server-addr: 192.168.1.102:8848

spring:
  application:
    name: nacos
  cloud:
    nacos:
      #服务注册地址
      discovery:
        server-addr: ${nacos.server-addr}
      config:
        #配置连接地址
        server-addr: ${nacos.server-addr}
        #命名空间
        namespace: Public
        #配置群组
        group: DEFAULT_GROUP
        #配置文件名
        prefix: nacos
        #配置文件后缀
        file-extension: yaml
        #动态刷新
        refresh-enabled: false
