server:
  port:


spring:
  application:
    name: NETTY-STUDY

#eureka
eureka:
  instance:
    hostname: localhost
    appname: Elastic
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      defaultZone: http://localhost:8761/eureka
